version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vrteste

  nest-js:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-js
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: vrteste